---
daq_options:
 compressRawData: yes
 nEvent: 1000
 externalChargeInjection: yes
 acquisitionType: sweep
 channelIds: [10]
 channelIdsToMask: [22]
 channelIdsDisableTOT: [22]
 channelIdsDisableTOA: [22]
 injectionDAC: 1000
 pulseDelay: 72
 preampFeedbackCapacitance: 8 
 totDACThreshold: 200
glb_options:
 moduleNumber: 63_HV200_test
 outputRawDataPath: data
 outputYamlPath: yaml
 storeYamlFile: yes
 startServerManually: no
 serverIpAdress: 194.12.171.221
 serverCodePath: /home/pi/arnaud-dev/rpi-daq
...
