---
daq_options:
 compressRawData: yes
 nEvent: 100
 externalChargeInjection: yes
 acquisitionType: sweep
 channelIds: [10]
 channelIdsToMask: [22]
 channelIdsDisableTOT: [22]
 channelIdsDisableTOA: [22]
 injectionDAC: 1000
 pulseDelay: 72
 preampFeedbackCapacitance: 8 
 totDACThreshold: 200
 shapingTime: 40
glb_options:
 moduleNumber: a_very_descriptive_string
 outputRawDataPath: data
 outputYamlPath: yaml
 storeYamlFile: yes
 startServerManually: no
 serverIpAdress: localhost
 serverCodePath: /home/pi/rpi-daq
...
