---
daq_options:
 compressRawData: yes
 nEvent: 1000
 externalChargeInjection: no
 acquisitionType: standard
 channelIds: []
 channelIdsToMask: []
 channelIdsDisableTOT: []
 channelIdsDisableTOA: []
glb_options:
 moduleNumber: 63_NoHV
 outputPath: data
...
