---
daq_options:
 compressRawData: yes
 nEvent: 100
 externalChargeInjection: no
 acquisitionType: standard
 channelIds: []
 channelIdsToMask: []
 channelIdsDisableTOT: []
 channelIdsDisableTOA: []
 injectionDAC: 1000
glb_options:
 moduleNumber: 63_NoHV
 outputRawDataPath: data
 outputYamlPath: yaml
 storeYamlFile: yes
 startServerManually: no
 serverIpAdress: 194.12.171.221
 serverCodePath: /home/pi/arnaud-dev/rpi-daq
...
